languaje: node_js
node_js:
    - "4.0"
scritp:
    - CD .\src
    - echo %cd%
    - echo 'install of bower'
    - call bower cache clean
    - call bower install
    - echo 'GULP me''
    - cd ..\
    - echo %cd%
    - echo 'install of npm'
    - call npm install
    - echo 'Building the site''
    - call gulp build
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --token $FIREBASE_TOKEN